### PR TITLE
Fixing UnordereObjectList warnings.

### PR DESCRIPTION
**Pull request by vinioleh**
Added ordering for unordered queryset.

### CODE REVIEW

**Comment by vinioleh** [comment]
This PR refers to https://github.com/elkrange/maroon-bells/issues/3723

**Review by cfshufeldt — CHANGES_REQUESTED** [review]
Glad this wasn't very complicated to fix. Can you add a test to the test suite for this method that only passes in the scenario where the warning won't be generated? I don't think testing for the warning is the correct approach. I would test for the condition that triggers the warning.

**Comment by vinioleh** [comment]
> Glad this wasn't very complicated to fix. Can you add a test to the test suite for this method that only passes in the scenario where the warning won't be generated? I don't think testing for the warning is the correct approach. I would test for the condition that triggers the warning.

Sure, I will add some tests. Thanks for the suggestion.

**Comment by vinioleh** [comment]
@cfshufeldt Test was added could you please check. In this library not test coverage only plug in pytest cases. the same situation with pylint.

**Review by cfshufeldt — APPROVED** [review]

**Comment by cfshufeldt** [comment]
This looks fine. Please set up issues to complete the following work as separate PRs:
- [ ] Add pre-commit and pre-commit.ci to this project to enforce code quality. Add appropriate badges to the readme.
- [ ] Add github actions ci workflow to run the test suite

**Pull request merged**
